<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #db3c22;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>
<h1>DEVELOPERS SAC</h1>
<div>Listado de Empleados</div>
<br>
<div>
    <form method="post">
        <label for="email">Buscar por Email</label>
        <input type="email" name="email">
        <button>Buscar</button>
    </form>
</div>
<br>

<div style="text-align: center">
    <table style="margin: 0 auto;text-align: left;">
        <thead>
        <tr>

            <th>Name</th>
            <th>Email</th>
            <th>Position</th>
            <th>Salary</th>
            <th>Opcion</th>
        </tr>
        </thead>
        <tbody>



        <?php  foreach ($employees as $item){

            ?>
            <tr>
                <td><?=  $item['name'] ?></td >
                <td ><?= $item['email'] ?> </td >
                <td ><?= $item['position'] ?> </td >
                <td ><?= $item['salary'] ?></td >
                <td><a href="../public/employee/<?= $item['id'] ?>">Ver</a></td>
            </tr>
        <?php }
        ?>
        </tbody>
    </table>
</div>



</body>
</html>
